# Generated by Django 4.2.1 on 2023-05-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_visit_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_visit', to='api.order', verbose_name='Заказ'),
        ),
    ]
