# Generated by Django 4.2.1 on 2023-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_visit_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('ended', 'ended'), ('in process', 'in process'), ('awaiting', 'awaiting'), ('canceled', 'canceled')], default='started', max_length=100),
            preserve_default=False,
        ),
    ]
